name: CI

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "MANIFEST.in"
      - "README.md"
  pull_request:
  workflow_dispatch: {}

jobs:
  build:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tests
      run: python tests.py

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: psf/black@stable
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Lint with ruff
      run: |
        ruff check

    - name: Lint with pylint
      run: |
        pylint cddlparser

    - name: Lint with mypy
      run: |
        mypy
